Berkman\SlideshowBundle\Entity\Image:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    id_1:
      type: string
    id_2:
      type: string
    id_3:
      type: string
  oneToOne:
    from_repo:
      targetEntity: Repo
