Berkman\SlideshowBundle\Entity\Repo:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    search_url_pattern:
      type: string
    record_url_pattern:
      type: string
    image_url_pattern:
      type: string
    metadata_url_pattern:
      type: string
  oneToOne:
    result_code:
      targetEntity: ResultFormat
      joinColumns:
        repo_code:
          referencedColumnName: code
