Berkman\SlideshowBundle\Entity\Slideshow:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
    slide_delay:
      type: smallint
    display_info:
      type: boolean
  manyToOne:
    person:
      targetEntity: Person
      inversedBy: Slideshow
  oneToMany:
    slides:
      targetEntity: Slide
      mappedBy: Slideshow
