parameters:
#    berkman_fos_user_child.example.class: Berkman\FOSUserChildBundle\Example

services:
#    berkman_fos_user_child.example:
#        class: %berkman_fos_user_child.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
