parameters:
#    berkman_fetcher.example.class: Berkman\FetcherBundle\Example

services:
#    berkman_fetcher.example:
#        class: %berkman_fetcher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
