security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        main:
            pattern:  .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    true
                check_path:     /login_check
                failure_path:   null
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/(_(profiler|wdt)|css|images|js)/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Slideshow permission stuff
        - { path: ^/slideshow/(new|create|edit|update|delete|addImage), role: IS_AUTHENTICATED_REMEMBERED }
        # Repo permission stuff
        - { path: ^/repo/\w*/(edit|update|delete), role: ROLE_ADMIN }
        - { path: ^/repo/(new|create), role: ROLE_ADMIN }
        - { path: ^/repo/\w*/import, role: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
        connection: default
