Berkman\CatalogBundle\Catalog\Catalog:
  type: entity
  id:
    id:
      type: string
      length: 10
  fields:
    name:
      type: string
    created:
      type: datetime
    updated:
      type: datetime
