Berkman\CatalogBundle\Entity\Image:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    catalog:
      type: string
    id_1:
      type: string
    id_2:
      type: string
      nullable: TRUE
    id_3:
      type: string
      nullable: TRUE
    id_4:
      type: string
      nullable: TRUE
    id_5:
      type: string
      nullable: TRUE
    id_6:
      type: string
      nullable: TRUE
