BerkmanSlideshowBundle_repo:
    resource: "@BerkmanSlideshowBundle/Resources/config/routing/repo.yml"
    prefix:   /repo

BerkmanSlideshowBundle_slideshow:
    resource: "@BerkmanSlideshowBundle/Resources/config/routing/slideshow.yml"
    prefix:   /slideshow

BerkmanSlideshowBundle_finder:
    resource: "@BerkmanSlideshowBundle/Resources/config/routing/finder.yml"
    prefix:   /find

BerkmanSlideshowBundle_homepage:
    pattern:  /
    defaults: { _controller: BerkmanSlideshowBundle:Finder:index }
