BerkmanSlideshowBundle_slideshow:
    resource: "@BerkmanSlideshowBundle/Resources/config/routing/slideshow.yml"
    prefix:   /slideshow

BerkmanSlideshowBundle_feedback:
    pattern:  /feedback
    defaults: { _controller: BerkmanSlideshowBundle:Feedback:index }

BerkmanSlideshowBundle_faqs: 
    pattern: /faq
    defaults: { _controller: BerkmanSlideshowBundle:Slideshow:faq }
