parameters:
    berkman_slideshow.image.class: Berkman\SlideshowBundle\Entity\Image
    berkman_slideshow.image_group.class: Berkman\SlideshowBundle\Entity\ImageGroup

services:
    berkman_slideshow.image:
        class: %berkman_slideshow.image.class%
    berkman_slideshow.image_group:
        class: %berkman_slideshow.image_group.class%
