slideshow:
    pattern:  /
    defaults: { _controller: "BerkmanSlideshowBundle:Finder:index" }

slideshow_show:
    pattern:  /{id}/show
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:show" }

slideshow_new:
    pattern:  /new
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:new" }

slideshow_create:
    pattern:  /create
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:create" }
    requirements: { _method: post }

slideshow_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:edit" }

slideshow_update:
    pattern:  /{id}/update
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:update" }
    requirements: { _method: post }

slideshow_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:delete" }
    requirements: { _method: post }

slideshow_add_images:
    pattern: /addImages
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:addImages" }

slideshow_slideshow:
    pattern: /{id}/slideshow
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:slideshow" }

slideshow_import:
    pattern: /import
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:import" }

slideshow_import_upload:
    pattern: /import/upload
    defaults: { _controller: "BerkmanSlideshowBundle:Slideshow:importUpload" }
    requirements: { _method: post }
