Berkman\SlideshowBundle\Entity\Catalog:
  type: entity
  id:
    id:
      type: string
      length: 10
  fields:
    name:
      type: string
    created:
      type: datetime
    updated:
      type: datetime
    isSearchable:
      type: boolean
    canImport:
      type: boolean
