Berkman\SlideshowBundle\Entity\Collection:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    id_1:
      type: string
    id_2:
      type: string
      nullable: TRUE
    id_3:
      type: string
      nullable: TRUE
    id_4:
      type: string
      nullable: TRUE
  oneToMany:
    children:
      targetEntity: Collection
      mappedBy: parent
  manyToOne:
    repo:
      targetEntity: Repo
    parent:
      targetEntity: Collection
      inversedBy: children
  manyToMany:
    images:
      targetEntity: Image
      mappedBy: collections
      cascade: ["persist", "remove"]

