Berkman\SlideshowBundle\Entity\Finder:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    results_per_page:
      type: integer
    keyword:
      type: string
      nullable: TRUE
    current_page:
      type: integer
    total_results:
      type: integer
      nullable: TRUE
    repo_indexes:
      type: string
      nullable: TRUE
  manyToMany:
    repos:
      targetEntity: Repo
    current_image_results:
      targetEntity: Image
      cascade: ["remove"]
      joinTable:
        name: finder_current_image_results
        joinColumns:
          finder_id:
            referencedColumnName: id
        inverseJoinColumns:
          image_id:
            referencedColumnName: id
    current_collection_results:
      targetEntity: Collection
      cascade: ["remove"]
      joinTable:
        name: finder_current_collection_results
        joinColumns:
          finder_id:
            referencedColumnName: id
        inverseJoinColumns:
          collection_id:
            referencedColumnName: id
    selected_image_results:
      targetEntity: Image
      cascade: ["remove"]
      joinTable:
        name: finder_selected_image_results
        joinColumns:
          finder_id:
            referencedColumnName: id
        inverseJoinColumns:
          image_id:
            referencedColumnName: id
    selected_colletion_results:
      targetEntity: Collection
      cascade: ["remove"]
      joinTable:
        name: finder_selected_collection_results
        joinColumns:
          finder_id:
            referencedColumnName: id
        inverseJoinColumns:
          collection_id:
            referencedColumnName: id
