Berkman\SlideshowBundle\Entity\ImageCollection:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    id_1:
      type: string
    id_2:
      type: string
      nullable: TRUE
  manyToOne:
    repo:
      targetEntity: Repo
  manyToMany:
    images:
      targetEntity: Image
      mappedBy: collections
      cascade: ["persist"]

