Berkman\SlideshowBundle\Entity\Person:
  type: entity
  name: person
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      unique: TRUE
    password:
      type: string
  oneToMany:
    slideshows:
      targetEntity: Slideshow
      mappedBy: person
