Berkman\SlideshowBundle\Entity\Person:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  oneToMany:
    slideshows:
      targetEntity: Slideshow
      mappedBy: person

