Berkman\SlideshowBundle\Entity\Slideshow:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
    slide_delay:
      type: smallint
    always_show_info:
      type: boolean
    display_controls:
      type: boolean
  manyToOne:
    person:
      targetEntity: Person
      inversedBy: slideshow
  oneToMany:
    slides:
      targetEntity: Slide
      mappedBy: slideshow
      cascade: ["persist", "remove"]
