Berkman\SlideshowBundle\Entity\Slide:
  type: entity
  table: slide
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    position:
      type: integer
  oneToOne:
    image:
      targetEntity: Image
  manyToOne:
    slideshow:
      targetEntity: Slideshow
      inversedBy: slide
#  uniqueConstraints:
#    slideshow_position:
#      columns: [slideshow_id, position]
