catalog:
    pattern:  /
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:index" }

catalog_show:
    pattern:  /{id}/show
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:show" }

catalog_new:
    pattern:  /new
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:new" }

catalog_create:
    pattern:  /create
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:create" }
    requirements: { _method: post }

catalog_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:edit" }

catalog_update:
    pattern:  /{id}/update
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:update" }
    requirements: { _method: post }

catalog_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:delete" }
    requirements: { _method: post }

catalog_import:
    pattern:  /{id}/import
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:import" }
    requirements: { _method: post }

catalog_import_progress:
    pattern:  /progress
    defaults: { _controller: "BerkmanCatalogBundle:Catalog:getProgress" }
