finder_index:
    pattern: /
    defaults: { _controller: "BerkmanCatalogBundle:Finder:index" }

finder_imageGroup:
    pattern: /imageGroup/{imageGroupId}/{page}
    defaults: { _controller: "BerkmanCatalogBundle:Finder:showImageGroup", page: 1 }

finder_submit:
    pattern: /submit
    defaults: { _controller: "BerkmanCatalogBundle:Finder:submit" }
    requirements: { _method: post }

finder_master_import:
    pattern: /import/master
    defaults: { _controller: "BerkmanCatalogBundle:Finder:masterImport" }
    requirements: { _method: post }

finder_custom_import:
    pattern: /import/custom
    defaults: { _controller: "BerkmanCatalogBundle:Finder:customImport" }
    requirements: { _method: post }

finder_show:
    pattern:  /{catalogIds}/{keyword}/{page}
    defaults: { _controller: "BerkmanCatalogBundle:Finder:show", page: 1 }
