<?php

namespace Berkman\SlideshowBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Cookie;
use Berkman\SlideshowBundle\Entity;
use Berkman\SlideshowBundle\Form\FinderType;
use Berkman\SlideshowBundle\Form\FinderResultsType;
use Berkman\SlideshowBundle\Form\ImportType;

/**
 * Finder controller.
 *
 * Notes:
 *   - Finder objects are now stuck in the session object instead of the database.
 *   - This necessitates certain changes:
 *        + IDs of objects (images, imageGroups) are going to have to be generated by something 
 *          other than the database
 *        + Catalog objects are going to be weird and wacky.  When persisting the images from
 *          the finder object, we'll have to pull the catalog from the database by ID and assign
 *          to the image and imageGroup objects.
 */
class FinderController extends Controller
{
    /**
     * Show the search form.
     *
     */
    public function indexAction()
    {
        $importForms = array();
        $request    = $this->getRequest();
        $em         = $this->getDoctrine()->getEntityManager();
        $catalogs   = $em->getRepository('BerkmanSlideshowBundle:Catalog')->findAll();
        $slideshows = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->findAll();
        $finder     = new Entity\Finder($catalogs);
        $finderForm = $this->createForm(new FinderType(), $finder);
        $masterForm = $this->createForm(new ImportType());
        foreach ($catalogs as $catalog) {
            if ($catalog->hasCustomImporter()) {
                $importForms[$catalog->getId()] = $this->createForm(new ImportType())->createView();
            }
        }
        
        if ('POST' === $request->getMethod()) {
            $finderForm->bindRequest($request);

            if ($finderForm->isValid()) {
                $catalogIds = array();
                $catalogs = $finder->getCatalogs();
                foreach ($catalogs as $catalog) {
                    $catalogIds[] = $catalog->getId();
                }

                return $this->redirect($this->generateUrl('finder_show', array(
                    'catalogs'   => implode('_', $catalogIds),
                    'keyword' => $finder->getKeyword(),
                    'page'    => 1
                )));
            }
        }
        else {
            return $this->render('BerkmanSlideshowBundle:Finder:index.html.twig', array(
                'catalogs' => $catalogs,
                'slideshows' => $slideshows,
                'master_form' => $masterForm->createView(),
                'import_forms' => $importForms,
                'finderForm'  => $finderForm->createView()
            ));
        }

    }

    /**
     * Show the search results.
     *
     * @param string $catalogs  A '_' separated list of catalog IDs
     * @param string $keyword  The keyword for which to search
     * @param int $page  The page of search results to fetch
     *
     * @return Response
     *
     * Note: These next two functions pretty much repeat each other - they shouldn't
     */
    public function showAction($catalogs, $keyword, $page = 1)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $catalogs = $em->getRepository('BerkmanSlideshowBundle:Catalog')->findBy(array(
            'id' => explode('_', $catalogs)
        ));
        if (!$catalogs) {
            throw $this->createNotFoundException('Unable to find Catalogs.');
        }

        $finder = $this->getFinder();
        $finder->setHierarchyStack(array($this->getRequest()->getUri()));
        $finder->setCatalogs($catalogs);
        $output = $finder->findResults($keyword, $page);

        $this->setFinder($finder);

        return $this->render('BerkmanSlideshowBundle:Finder:show.html.twig', array(
            'finder'      => $finder,
            'images'      => $finder->getCurrentImageResults(),
            'imageGroups' => $finder->getCurrentImageGroupResults(),
        ));
    }

    /**
     * Show the results of a imageGroup search
     * 
     * @param string $imageGroupId  The id of the imageGroup to show
     * @param int $page  The page to fetch
     *
     * @return Response
     *
     */
    public function showImageGroupAction($imageGroupId, $page = 1)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $finder = $this->getFinder();
        if ($page == 1) {
            $finder->pushHierarchyStack($this->getRequest()->getUri());
        }

        $imageGroup = $finder->getImageGroup($imageGroupId);
        if (!$imageGroup) {
            throw $this->createNotFoundException('Unable to find imagegroup.');
        }

        $output = $finder->findImageGroupResults($imageGroup, $page);
        $this->setFinder($finder);

        return $this->render('BerkmanSlideshowBundle:Finder:show.html.twig', array(
            'finder'      => $finder,
            'images'      => $finder->getCurrentImageResults(),
            'imageGroups' => $finder->getCurrentImageGroupResults(),
            'imageGroupId'=> $imageGroupId
        ));
    }

    /**
     * Handle the submission of the search results form
     * 
     * There are a few ways in which the form can be submitted:
     *   - Previous page button
     *   - Next page button
     *   - View ImageGroup button
     *   - Finish button
     * The selected images and imageGroup should be saved no matter the method
     *
     */
    public function submitAction()
    {
        $request   = $this->getRequest();
        $em        = $this->getDoctrine()->getEntityManager();
        $finder    = $this->getFinder();
        $response  = $this->redirect($this->generateUrl('slideshow_add_images'));

        $images = $request->get('images');
        if (!empty($images)) {
            foreach ($images as $image_id) {
                $finder->addSelectedImageResult($image_id); 
            }
        }

        $imageGroups = $request->get('imageGroups');
        if (!empty($imageGroups)) {
            foreach ($imageGroups as $imageGroup_id) {
                $images = $finder->getImageGroup($imageGroup_id)->getAllImages();
                foreach ($images as $image) {
                    $finder->addSelectedImageResult($finder->addImage($image));
                }
            }
        }

        if ($request->isXmlHttpRequest()) {
            return $this->render('BerkmanSlideshowBundle:Finder:addImages.json.twig', array(
                'finderImages' => count($finder->getSelectedImageResults())
            ));
        }

        $catalogIds = array();
        $catalogs = $finder->getCatalogs();
        foreach ($catalogs as $catalog) {
            $catalogIds[] = $catalog->getId();
        }

        if (in_array($request->get('action'), array('Next Page >', '< Previous Page'))) {
            $page = ($request->get('action') == 'Next Page >') ?
                $finder->getCurrentPage() + 1 : $finder->getCurrentPage() - 1;
            //This would mean we're browsing an image group
            if ($request->get('imageGroupId') != null) {
                $response = $this->redirect($this->generateUrl('finder_imageGroup', array(
                    'imageGroupId' => $request->get('imageGroupId'),
                    'page' => $page
                )));
            }
            else {
                $response = $this->redirect($this->generateUrl('finder_show', array(
                    'catalogs' => implode('_', $catalogIds),
                    'keyword' => $finder->getKeyword(),
                    'page' => $page
                )));
            }
        }
        elseif ($request->get('action') == 'Back') {
            $finder->popHierarchyStack();
            $uri = $finder->popHierarchyStack();
            $response = $this->redirect($uri);
        }
        elseif ($request->get('action') != 'Finish') {
            $response = $this->redirect($this->generateUrl('finder_imageGroup', array(
                'imageGroupId' => $request->get('action')
            )));
        }

        $this->setFinder($finder);

        return $response;
    }

    /**
     * Get the Finder object for the current session
     * or make a new one.
     *
     * @return Berkman\SlideshowBundle\Entity\Finder
     */
    private function getFinder()
    {
        $finder = $this->getRequest()->getSession()->get('finder');
        if (!$finder) {
            $finder = new Entity\Finder();
            $this->setFinder($finder);
        }

        return $finder;
    }

    /**
     * Assign some Finder object to the current session
     *
     * @param Berkman\SlideshowBundle\Entity\Finder $finder
     */
    private function setFinder(Entity\Finder $finder)
    {
        $this->getRequest()->getSession()->set('finder', $finder);
    }
}
