<?php

namespace Berkman\SlideshowBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Cookie;
use Berkman\SlideshowBundle\Entity;
use Berkman\SlideshowBundle\Form\FinderType;
use Berkman\SlideshowBundle\Form\FinderResultsType;

/**
 * Finder controller.
 *
 * Notes:
 *   - Finder objects are now stuck in the session object instead of the database.
 *   - This necessitates certain changes:
 *        + IDs of objects (images, collections) are going to have to be generated by something 
 *          other than the database
 *        + Catalog objects are going to be weird and wacky.  When persisting the images from
 *          the finder object, we'll have to pull the catalog from the database by ID and assign
 *          to the image and collection objects.
 */
class FinderController extends Controller
{
    /**
     * Show the search form.
     *
     */
    public function indexAction()
    {
        $request    = $this->getRequest();
		$em         = $this->getDoctrine()->getEntityManager();
		$catalogs      = $em->getRepository('BerkmanSlideshowBundle:Catalog')->findAll();
		$slideshows = $em->getRepository('BerkmanSlideshowBundle:Slideshow')->findAll();
		$finder     = new Entity\Finder($catalogs);
        $finderForm = $this->createForm(new FinderType(), $finder);
		
        if ('POST' === $request->getMethod()) {
            $finderForm->bindRequest($request);

            if ($finderForm->isValid()) {
				$catalogIds = array();
				$catalogs = $finder->getCatalogs();
				foreach ($catalogs as $catalog) {
					$catalogIds[] = $catalog->getId();
				}

				return $this->redirect($this->generateUrl('finder_show', array(
					'catalogs'   => implode('_', $catalogIds),
					'keyword' => $finder->getKeyword(),
					'page'    => 1
				)));
            }
        }
		else {
			return $this->render('BerkmanSlideshowBundle:Finder:index.html.twig', array(
                'slideshows' => $slideshows,
				'finderForm'  => $finderForm->createView()
			));
		}

    }

    /**
     * Show the search results.
     *
     * @param string $catalogs  A '_' separated list of catalog IDs
     * @param string $keyword  The keyword for which to search
     * @param int $page  The page of search results to fetch
     *
     * @return Response
     *
     * Note: These next two functions pretty much repeat each other - they shouldn't
     */
    public function showAction($catalogs, $keyword, $page = 1)
    {
		$em = $this->getDoctrine()->getEntityManager();
		$catalogs = $em->getRepository('BerkmanSlideshowBundle:Catalog')->findBy(array(
			'id' => explode('_', $catalogs)
		));
		if (!$catalogs) {
			throw $this->createNotFoundException('Unable to find Catalogs.');
		}

        $finder = $this->getFinder();
        $finder->setCatalogs($catalogs);
		$output = $finder->findResults($keyword, $page);

        $this->setFinder($finder);

		return $this->render('BerkmanSlideshowBundle:Finder:show.html.twig', array(
            'finder'      => $finder,
            'images'      => $finder->getCurrentImageResults(),
            'collections' => $finder->getCurrentCollectionResults(),
            'showing'     => 'results'
        ));
    }

    /**
     * Show the results of a collection search
     * 
     * @param string $collectionId  The id of the collection to show
     * @param int $page  The page to fetch
     *
     * @return Response
     *
     */
    public function showCollectionAction($collectionId, $page = 1)
    {
		$em = $this->getDoctrine()->getEntityManager();
        $finder = $this->getFinder();

		$collection = $finder->getCollection($collectionId);
		if (!$collection) {
			throw $this->createNotFoundException('Unable to find Collection.');
		}

		$output = $finder->findCollectionResults($collection, $page);
        $this->setFinder($finder);

		return $this->render('BerkmanSlideshowBundle:Finder:show.html.twig', array(
            'finder'      => $finder,
            'images'      => $finder->getCurrentImageResults(),
            'collections' => $finder->getCurrentCollectionResults(),
            'showing'     => 'collection',
            'referrer'    => $_SERVER['HTTP_REFERER']
        ));
    }

    /**
     * Handle the submission of the search results form
     * 
     * There are a few ways in which the form can be submitted:
     *   - Previous page button
     *   - Next page button
     *   - View Collection button
     *   - Finish button
     * The selected images and collection should be saved no matter the method
     *
     */
	public function submitAction()
	{
		$request   = $this->getRequest();
        $em        = $this->getDoctrine()->getEntityManager();
        $finder    = $this->getFinder();
		$response  = $this->redirect($this->generateUrl('slideshow_add_images'));

		$images = $request->get('images');
		if (!empty($images)) {
            foreach ($images as $image_id) {
                $finder->addSelectedImageResult($image_id); 
            }
		}

		$collections = $request->get('collections');
		if (!empty($collections)) {
            foreach ($collections as $collection_id) {
                $images = $finder->getCollection($collection_id)->getAllImages();
                foreach ($images as $image) {
                    $finder->addSelectedImageResult($finder->addImage($image));
                }
            }
		}

        $this->setFinder($finder);

        if ($request->isXmlHttpRequest()) {
            return $this->render('BerkmanSlideshowBundle:Finder:addImages.json.twig', array(
                'finderImages' => count($finder->getSelectedImageResults())
            ));
        }

        $catalogIds = array();
        $catalogs = $finder->getCatalogs();
        foreach ($catalogs as $catalog) {
            $catalogIds[] = $catalog->getId();
        }

		if (in_array($request->get('action'), array('Next Page', 'Previous Page'))) {
            $page = ($request->get('action') == 'Next Page') ?
                $finder->getCurrentPage() + 1 : $finder->getCurrentPage() - 1;
			$response = $this->redirect($this->generateUrl('finder_show', array(
				'catalogs' => implode('_', $catalogIds),
				'keyword' => $finder->getKeyword(),
				'page' => $page
			)));
		}
        elseif ($request->get('action') == 'Back') {
            $response = $this->redirect($request->get('referrer'));
        }
        elseif ($request->get('action') != 'Finish') {
            $response = $this->redirect($this->generateUrl('finder_collection', array(
                'collectionId' => $request->get('action')
            )));
        }

		return $response;
	}

    /**
     * Get the Finder object for the current session
     * or make a new one.
     *
     * @return Berkman\SlideshowBundle\Entity\Finder
     */
    private function getFinder()
    {
        $finder = $this->getRequest()->getSession()->get('finder');
        if (!$finder) {
            $finder = new Entity\Finder();
            $this->setFinder($finder);
        }

        return $finder;
    }

    /**
     * Assign some Finder object to the current session
     *
     * @param Berkman\SlideshowBundle\Entity\Finder $finder
     */
    private function setFinder(Entity\Finder $finder)
    {
        $this->getRequest()->getSession()->set('finder', $finder);
    }
}
